language: java
jdk:
  - openjdk8

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test

before install: 
  - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:8-jdk-alpine
  #deploying the app on Docker & Heroku
  - mvn deploy
  
root: linux

jobs:
  include:
    - stage: Test
      script: mvn test

notification:
  email: jennypereira121996@gmail.com
