language: java
jdk:
  - openjdk8

services: 
  #Linking Travis CI and Docker
  - docker

#install:
#  - ./mvnw clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V 

before install: 
  - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:8-jdk-alpine
  #deploying the app on Docker & Heroku
