language: java
jdk:
  - openjdk8

install:
  - mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn deploy

before install: 
  - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:8-jdk-alpine
  #deploying the app on Docker & Heroku
  #mvn deploy
  
root: linux

notification:
  email: jennypereira121996@gmail.com
