sudo: required
language: java
jdk: openjdk8

addons:
  sonarcloud:
    organization: "CICD-APP"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

services: 
  #Linking Travis CI and Docker
  - docker

before install: 
  #- mvn install
  - chmod +x mvnw
  
script: 
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  
#install: mvn install

cache:
  directories:
    - '$HOME/.m2/settings.xml'

after_success:
#Generating Site
- travis_wait mvn site
- bash <(curl -s https://codecov.io/bash)
# SonarCloud
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
