sudo: required
language: java
jdk: openjdk8

services: 
  #Linking Travis CI and Docker
  - docker

before install: 
  - chmod +x mvnw

install: 
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: 
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

cache:
  directories:
    - '$HOME/.m2/repository'
