sudo: required
language: java
jdk: openjdk8

services: 
  #Linking Travis CI and Docker
  - docker

before install: 
  - chmod +x mvnw

script: 
  - ./mvnw clean install -B

cache:
  directories:
    - '$HOME/.m2/repository'
