sudo: required
language: java
jdk: openjdk8

services: 
  #Linking Travis CI and Docker
  - docker

before install: 
  #- mvn clean
  - chmod +x mvnw
  - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:8-jdk-alpine

install: 
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

cache:
  directories:
    - '$HOME/.m2/repository'
